Update merged-workflow.yml

diff --git a/.github/workflows/merged-workflow.yml b/.github/workflows/merged-workflow.yml
--- a/.github/workflows/merged-workflow.yml
+++ b/.github/workflows/merged-workflow.yml
@@ -61,15 +61,15 @@ jobs:
           password: ${{ secrets.GIT_PAT }}
 
 
-      - name: Build Docker image api service
-        run: |
-          cd automation-api-service-generator
-          echo "TAG in this step: $TAG"
-          IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
-          docker build -t $IMAGE_NAME:$TAG .
-          echo "$TAG"
-        env:
-          DOCKER_BUILDKIT: 1
+      # - name: Build Docker image api service
+      #   run: |
+      #     cd automation-api-service-generator
+      #     echo "TAG in this step: $TAG"
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+      #     docker build -t $IMAGE_NAME:$TAG .
+      #     echo "$TAG"
+      #   env:
+      #     DOCKER_BUILDKIT: 1
 
       - name: Run container locally
         run: |
@@ -141,59 +141,51 @@ jobs:
 
           EOF
           fi
-            
-          # docker run -d --rm --name api-test \
+
+
+          # docker run -d --name api-test \
           #   -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
-          #   --env-file ./.env \
+          #   --env-file .env \
           #   $IMAGE_NAME:$TAG
+      
+          # echo "⏳ Waiting for service..."
           # sleep 5
-
-          docker run -d --name api-test \
-            -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
-            --env-file .env \
-            $IMAGE_NAME:$TAG
       
-          echo "⏳ Waiting for service..."
-          sleep 5
+          # echo "📋 Container status:"
+          # docker ps -a
       
-          echo "📋 Container status:"
-          docker ps -a
-      
-          echo "📜 Logs:"
-          docker logs api-test || true
-      
-          # echo "🔍 Health check:"
-          # curl -v http://localhost:${{ vars. API_SERVICE_PORT }}/health || true
+          # echo "📜 Logs:"
+          # docker logs api-test || true
 
-      - name: Healthcheck
-        run: |
-          HEALTHCHECK_URL="http://localhost:${{ vars.API_SERVICE_PORT}}/api-service/${{ vars.DOMAIN }}/${{vars.VERSION}}/health"
-          echo "Checking $HEALTHCHECK_URL ..."
-          for i in {1..10}; do
-            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-              echo "✅ Container is healthy"
-              exit 0
-            fi
-            echo "Waiting... ($i)"
-            sleep 2
-          done
-          echo "❌ Healthcheck failed!"
-          docker logs api-test
-          exit 1
+      # - name: Healthcheck
+      #   run: |
+      #     HEALTHCHECK_URL="http://localhost:${{ vars.API_SERVICE_PORT}}/api-service/${{ vars.DOMAIN }}/${{vars.VERSION}}/health"
+      #     echo "Checking $HEALTHCHECK_URL ..."
+      #     for i in {1..10}; do
+      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+      #         echo "✅ Container is healthy"
+      #         exit 0
+      #       fi
+      #       echo "Waiting... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "❌ Healthcheck failed!"
+      #     docker logs api-test
+      #     exit 1
 
-      - name: Stop test container
-        if: always()
-        run: docker stop api-test || true
+      # - name: Stop test container
+      #   if: always()
+      #   run: docker stop api-test || true
 
-      - name: Tag & Push Images
-        run: |
-          echo TAG in next step: $TAG
-          IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
-          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
-          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
-          docker push $IMAGE_NAME:$TAG
-          docker push $IMAGE_NAME:latest
-          docker push $IMAGE_NAME:stable
+      # - name: Tag & Push Images
+      #   run: |
+      #     echo TAG in next step: $TAG
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+      #     docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
+      #     docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
+      #     docker push $IMAGE_NAME:$TAG
+      #     docker push $IMAGE_NAME:latest
+      #     docker push $IMAGE_NAME:stable
 
 
   # build mock service 
@@ -225,15 +217,15 @@ jobs:
           password: ${{ secrets.GIT_PAT }}
 
 
-      - name: Build Docker image mock service
-        run: |
-          cd automation-mock-service-generator
-          echo "TAG in this step: $TAG"
-          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
-          docker build -t $IMAGE_NAME:$TAG .
-          echo "$TAG"
-        env:
-          DOCKER_BUILDKIT: 1
+      # - name: Build Docker image mock service
+      #   run: |
+      #     cd automation-mock-service-generator
+      #     echo "TAG in this step: $TAG"
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
+      #     docker build -t $IMAGE_NAME:$TAG .
+      #     echo "$TAG"
+      #   env:
+      #     DOCKER_BUILDKIT: 1
 
       - name: Run container locally
         run: |
@@ -278,11 +270,12 @@ jobs:
           #   $IMAGE_NAME:$TAG
           # sleep 5
 
-          docker run -d --name mock-test \
-            -p ${{ vars.MOCK_SERVICE_PORT }}:${{ vars.MOCK_SERVICE_PORT }} \
-            --env-file .env \
-            $IMAGE_NAME:$TAG
-      
+          # docker run -d --name mock-test \
+          #   -p ${{ vars.MOCK_SERVICE_PORT }}:${{ vars.MOCK_SERVICE_PORT }} \
+          #   --env-file .env \
+          #   $IMAGE_NAME:$TAG
+
+          # dont uncomment
           # echo "⏳ Waiting for service..."
           # sleep 5
       
@@ -295,35 +288,35 @@ jobs:
           # echo "🔍 Health check:"
           # curl -v http://localhost:${{ vars.MOCK_SERVICE_PORT }}/health || true
 
-      - name: Healthcheck
-        run: |
-          HEALTHCHECK_URL="http://localhost:${{ vars.MOCK_SERVICE_PORT }}/mock/${{ vars.DOMAIN }}/health"
-          echo "Checking $HEALTHCHECK_URL ..."
-          for i in {1..10}; do
-            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-              echo "✅ Container is healthy"
-              exit 0
-            fi
-            echo "Waiting... ($i)"
-            sleep 2
-          done
-          echo "❌ Healthcheck failed!"
-          docker logs mock-test
-          exit 1
+      # - name: Healthcheck
+      #   run: |
+      #     HEALTHCHECK_URL="http://localhost:${{ vars.MOCK_SERVICE_PORT }}/mock/${{ vars.DOMAIN }}/health"
+      #     echo "Checking $HEALTHCHECK_URL ..."
+      #     for i in {1..10}; do
+      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+      #         echo "✅ Container is healthy"
+      #         exit 0
+      #       fi
+      #       echo "Waiting... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "❌ Healthcheck failed!"
+      #     docker logs mock-test
+      #     exit 1
 
-      - name: Stop test container
-        if: always()
-        run: docker stop mock-test || true
+      # - name: Stop test container
+      #   if: always()
+      #   run: docker stop mock-test || true
 
-      - name: Tag & Push Images
-        run: |
-          echo TAG in next step: $TAG
-          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
-          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
-          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
-          docker push $IMAGE_NAME:$TAG
-          docker push $IMAGE_NAME:latest
-          docker push $IMAGE_NAME:stable
+      # - name: Tag & Push Images
+      #   run: |
+      #     echo TAG in next step: $TAG
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
+      #     docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
+      #     docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
+      #     docker push $IMAGE_NAME:$TAG
+      #     docker push $IMAGE_NAME:latest
+      #     docker push $IMAGE_NAME:stable
           
 #automation runner
       - name: Clone automation winx
